core/urls.py
from django.urls import path

from .views import (
    ShopView,
    ItemDetailView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    CheckoutView,
    payment_view,
    payment_complete,
    WalletView,
    WithdrawView,
    DepositView,
)

app_name = 'core'

urlpatterns = [
    path(r'',ShopView.as_view(),name='shop'),
    path(r'cart/',OrderSummaryView.as_view(),name='order-summary'),
    path(r'checkout/',CheckoutView.as_view(),name='checkout'),
    path(r'payment/',payment_view,name='payment'),
    path(r'payment_complete/',payment_complete,name='complete'),
    path(r'product/<slug>/', ItemDetailView.as_view(), name='product'),
    path(r'add_to_cart/<slug>/',add_to_cart,name='add-to-cart'),
    path(r'wallet/',WalletView.as_view(),name='wallet'),
    path(r'deposit_funds/',DepositView.as_view() ,name='deposit-funds'),
    path(r'withdraw_funds/',WithdrawView.as_view(),name='withdraw-funds'),
    path(r'remove_from_cart/<slug>/',remove_from_cart,name='remove-from-cart'),
    path(r'remove_single_item_from_cart/<slug>/',remove_single_item_from_cart, name='remove-single-item-from-cart'),
]

sneakerheads/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from .views import index_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path(r'',index_view,name='home'),
    path('shop/', include('core.urls')),
]

#appending the static files urls to the above media
urlpatterns += staticfiles_urlpatterns()
#how to upload media..appending the media url to the patterns above
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse

# Create your models here.

CATEGORY_CHOICES = (
    ('M','Men'),
    ('W','Women'),
    ('CH','Children'),
    ('WA','Wathces'),
    ('AJ','Air Jordan'),
    ('SW','Sport wear'),
    ('OW','Out wear')
)

ORDER_TYPE_CHOICES = (
    ('D','Deposit'),
    ('BG','Buy goods')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B','Billing'),
    ('S','Shipping')
)

TRANSACTION_CHOICES = (
    ('E','Earned'),
    ('S','Spent')
)

PAYMENT_CHOICES = (
    ('P','Paypal'),
    ('W','Wallet')
)

class UserProfile(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50,blank=True,null=True)
    paypal_customer_id  = models.CharField(max_length=50,blank=True,null=True)
    
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    id = models.AutoField(primary_key=True)
    charge_id = models.CharField(max_length=50,blank=True,null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class Address(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField( max_length=100)
    price = models.FloatField()
    thumbnail = models.FileField(blank=True,null=True)
    discount_price = models.FloatField(blank=True,null=True)
    label = models.CharField(choices=LABEL_CHOICES,max_length=1)
    category = models.CharField(choices=CATEGORY_CHOICES,max_length=2)
    slug = models.SlugField()
    description = models.TextField()
    date = models.DateTimeField( auto_now_add=True,blank=True,null=True)
    display_image_one = models.FileField( blank=True,null=True)
    display_image_two = models.FileField( blank=True,null=True)
    display_image_three = models.FileField( blank=True,null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={"slug": self.slug})

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart",kwargs={"slug":self.slug})
    
    def remove_from_cart_url(self):
        return reverse("core:remove-from-cart",kwargs={"slug":self.slug})


class OrderItem(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,blank=True,null=True)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.item.title

    def get_total_item_price(self):
        return self.item.price * self.quantity

    def get_total_discount_item_price(self):
        return self.item.discount_price * self.quantity

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()
        
    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        else:
            return self.get_total_item_price()

class Order(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    order_type = models.CharField(choices=ORDER_TYPE_CHOICES, max_length=2,blank=True,null=True)
    items = models.ManyToManyField(OrderItem,blank=True)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(auto_now_add=False)
    ordered = models.BooleanField(default=False)
    ref_code = models.CharField( max_length=50,blank=True,null=True)
    value = models.FloatField(default=0.0)

    #billing and shipping address of the order
    shipping_address = models.ForeignKey(
        Address, related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        Address, related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    
    payment = models.ForeignKey(Payment,  on_delete=models.SET_NULL, blank=True,null=True)

    def __str__(self):
        return self.user.username
        
    def get_total(self):
        for order_item in self.items.all():
            self.value += order_item.get_final_price()
        return self.value

class Wallet(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    balance = models.FloatField(default=0.0)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    id = models.AutoField(primary_key=True)
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code

class Refund(models.Model):
    id = models.AutoField(primary_key=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


class TransactionRecord(models.Model):
    id = models.AutoField(primary_key=True)
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE)
    date = models.DateTimeField( auto_now_add=True)
    amount = models.FloatField()
    transaction_type = models.CharField(max_length=1,choices=TRANSACTION_CHOICES)

    def __str__(self):
        return self.wallet.user.username
    

class DepositRequest(models.Model):
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE)
    amount = models.FloatField()
    order = models.ForeignKey(Order, on_delete=models.CASCADE,blank=True,null=True)
    date = models.DateTimeField( auto_now_add=True)

    def __str__(self):
        return self.wallet.user.username

templates/base_layout.htm
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}{% endblock %}</title>
    
    <!--Bootstrap CDN Links-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    {% block extra_head %}
    {% endblock extra_head %}
</head>
<body>
    
    <div>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>
    {%include 'nav.htm'%}

    {%block content%}   
    {%endblock%}


    {% include "footer.htm" %}
    {% include "scripts.htm" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/cart.htm
{% extends "base_layout.htm" %}
{%load static%}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'assets/cart.css' %}">
{% endblock extra_head %}
{% block content %}
<main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h1 class="my-5">Order Summary</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}" style='color: #001;'><i class="fa fa-minus mr-2"></i></a>
                <a href="{% url 'core:add-to-cart' order_item.item.slug %}" style='color: #c73161;'><i class="fa fa-plus ml-2"></i></a>
            </td>
            <td>
                {% if order_item.item.discount_price %}
                    ${{ order_item.get_total_discount_item_price }}
                    <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
                {% else %}
                    ${{ order_item.get_total_item_price }}
                {% endif %}
            </td>
            <td>
                <a style='color: #c73161;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                    <i class="fa fa-trash float-right"></i>
                </a>
            </td>
                
        </tr>
        {% empty %}
        <tr>
            <td colspan='6'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="6">
                <button class='buy-btn float-right btn-lg'>
                    <a href="/shop/">Continue shopping </a>
                </button>
            </td>
        </tr>
        {% endfor %}
        {% if object.get_total %}
        <tr>
            <td colspan="5"><b>Order Total</b></td>
            <td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="6">
            <button class='buy-btn float-right ml-2'>
                <a href="/shop/checkout/">Proceed to checkout</a>
            </button>
            <button class='buy-btn float-right btn-lg'>
                <a href="/shop/">Continue shopping </a>
            </button>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

  
{% endblock content %}

templates/deposit.htm
{%extends 'base_layout.htm'%}
{%load static%}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'assets/deposit.css' %}">
{% endblock extra_head %}
{% block content %}
<main>
    <div class="container">
      <h2 class="my-5 text-center">Deposit</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            <form method="POST" action="/shop/deposit_funds/" class="card-body">
              {%csrf_token%}
                <h2 class="my-5">Enter Amount you wish to deposit</h2>
                <div class='hideable_billing_form'>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                          <span class="input-group-text">$</span>
                        </div>
                        <input type="number" name="amount" class="form-control" aria-label="Amount (to the nearest dollar)">
                        <div class="input-group-append">
                          <span class="input-group-text">.00</span>
                        </div>
                      </div>
                    <button class="buy-btn" type="submit">Submit Amount</button>
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>
</main>
{% endblock %}

templates/index.htm
{%extends 'base_layout.htm'%}
{% load static %}
{%block content%}
<section id="home">
    <div class="container">
        <h5>NEW ARRIVALS</h5>
        <h1><span>Best Price</span> This Year</h1>
        <p>Get all your sneakers and clothes <br> from one place </p>
        <button>
            <a href="{%url 'core:shop' %}">Shop now </a>
        </button>
    </div>
</section>

<section id="brand" class="container">
    <div class="row m-0 py-5">
        <img class="img-fluid col-md-1 col-md-2 col-6" src="{% static 'assets/img/brand/1.png'%}" alt="">
        <img class="img-fluid col-md-1 col-md-2 col-6" src="{% static 'assets/img/brand/2.png'%}" alt="">
        <img class="img-fluid col-md-1 col-md-2 col-6" src="{% static 'assets/img/brand/3.png'%}" alt="">
        <img class="img-fluid col-md-1 col-md-2 col-6" src="{% static 'assets/img/brand/4.png'%}" alt="">
        <img class="img-fluid col-md-1 col-md-2 col-6" src="{% static 'assets/img/brand/5.png'%}" alt="">
        <img class="img-fluid col-md-1 col-md-2 col-6" src="{% static 'assets/img/brand/6.png'%}" alt="">
    </div>
</section>

<section id="new" class="w-100">
    <div class="row p-0 m-0">
        <div class="one col-lg-4 col-md-12 col-12 p-0">
            <img  class="img-fluid" src="{% static 'assets/img/new/1.jpg'%}" alt="">
            <div class="details">
                <h2>Latest Sneakers</h2>
                <button class="text-uppercase">
                    <a href="{%url 'core:shop' %}">Shop now </a>
                </button>
            </div>
        </div>
        <div class="one col-lg-4 col-md-12 col-12 p-0">
            <img  class="img-fluid" src="{% static 'assets/img/new/5.jpg'%}" alt="">
            <div class="details">
                <h2>Women's collection</h2>
                <button class="text-uppercase">
                    <a href="{%url 'core:shop' %}">Shop now </a>
                </button>
            </div>
        </div>
        <div class="one col-lg-4 col-md-12 col-12 p-0">
            <img  class="img-fluid" src="{% static 'assets/img/new/3.jpg'%}" alt="">
            <div class="details">
                <h2>Watches</h2>
                <button class="text-uppercase">
                    <a href="{%url 'core:shop' %}">Shop now </a>
                </button>
            </div>
        </div>
    </div>
</section>

<section id="featured" class="my-5 pb-5">
    <div class="container text-center mt-5 py-5">
        <h3>Our featured products</h3>
        <hr class="mx-auto">
        <p>Here you can check out our new products with fair price on sneakerheads</p>
    </div>
    <div class="row mx-auto container-fluid">
        {% for featured_item in featured_items %}
        <div class="product text-center col-lg-3 col-md-4 col-12">
            <img class="img-fluid mb-3" src="{{featured_item.thumbnail.url}}" alt="">
            <div class="star">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
            </div>
            <h5 class="p-name">
                <a href="{{ featured_item.get_absolute_url }}">{{ featured_item.title }}</a>
            </h5>
            <h4 class="p-price">
                <strong>$
                    {% if featured_item.discount_price %}
                    {{ featured_item.discount_price }}
                    {% else %}
                    {{ featured_item.price }}
                    {% endif %}
                </strong>
            </h4>
            <button class="buy-btn">
                <a href="{{ featured_item.get_add_to_cart_url }}">Buy Now</a>
            </button>
        </div>
    {% endfor %}
    </div>
</section>

<section id="banner" class="my-5 py-5">
    <div class="container">
        <h4>MID SEASON'S SALE</h4>
        <h1>Autumn Collection <br> UP TO 20% OFF</h1>
        <button class="text-uppercase">Shop Now</button>
    </div>
</section>

<section id="featured" class="my-5 pb-5">
    <div class="container text-center mt-5 py-5">
        <h3>More Clothes from Sneakerheads</h3>
        <hr class="mx-auto">
        <p>Shop all the best clothes from sneakerheads</p>
    </div>
    <div class="row mx-auto container-fluid">
        {% for item in items %}
        <div class="product text-center col-lg-3 col-md-4 col-12">
            <img class="img-fluid mb-3" src="{{item.thumbnail.url}}" alt="">
            <div class="star">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
            </div>
            <h5 class="p-name">
                <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
            </h5>
            <h4 class="p-price">
                <strong>$
                    {% if item.discount_price %}
                    {{ item.discount_price }}
                    {% else %}
                    {{ item.price }}
                    {% endif %}
                </strong>
            </h4>
            <button class="buy-btn">
                <a href="{{ item.get_add_to_cart_url }}">Buy Now</a>
            </button>
        </div>
    {% endfor %}
    </div>
</section>
<section id="featured" class="my-5 pb-5">
    <div class="container text-center mt-5 py-5">
        <h3>Best Watches</h3>
        <hr class="mx-auto">
        <p>Here you can find the best watches from sneakerheads</p>
    </div>
    <div class="row mx-auto container-fluid">
        {% for watch in watches %}
        <div class="product text-center col-lg-3 col-md-4 col-12">
            <img class="img-fluid mb-3" src="{{watch.thumbnail.url}}" alt="">
            <div class="star">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
            </div>
            <h5 class="p-name">
                <a href="{{ watch.get_absolute_url }}">{{ watch.title }}</a>
            </h5>
            <h4 class="p-price">
                <strong>$
                    {% if watch.discount_price %}
                    {{ watch.discount_price }}
                    {% else %}
                    {{ watch.price }}
                    {% endif %}
                </strong>
            </h4>
            <button class="buy-btn">
                <a href="{{ watch.get_add_to_cart_url }}">Buy Now</a>
            </button>
        </div>
    {% endfor %}
    </div>
</section>


{%endblock%}

templates/nav.htm
{%load cart_template_tags%}
<nav class="navbar navbar-expand-lg bg-light py-3">
    <div class="container">
    <a class="navbar-brand" href="index.html">Sneaker heads</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span id="bar" class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:shop' %}">Shop</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'core:wallet'%}">Wallet</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Blog</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Contact us</a>
            </li>
            {%if request.user.is_authenticated%}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:order-summary' %}">
                    <span>({{request.user|cart_item_count}})</span>
                    Cart
                </a>
            </li>
            <li class="nav-item">
                <a href="{%url 'account_logout'%}">logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a href="{%url 'account_login'%}">login</a>
            </li>
            <li class="nav-item">
                <a href="{%url 'account_signup'%}">signup</a>
            </li>
            {% endif %}
        </ul>
    </div>
    </div>
</nav>

templates/payment2.htm
{% extends "base_layout.htm" %}



{% block extra_head %}

{% endblock extra_head %}



{% block content %}
  <div class="container my-5 pt-5">
    <div class="card" style="width: 100%;">
      <div class="card-body">
        <h1>Payment Summary <br/>
          {% if order.order_type == 'BG' %}
           for Shopping
          {% else %}
          for a Deposit
          {% endif %}
        </h1>
        <p><bold>Reference ID:</bold> {{ order.ref_code }}</p>
        <p><bold>Total price:</bold> {{order.get_total}}</p>
        <p><bold>Billing Address:</bold> {{order.billing_address}}</p>
        {% if order.order_type == 'BG' %}
          <p><bold>Shipping Address:</bold> {{order.shipping_address}}</p>
        {% endif %} 
      </div>
      {% if order.order_type == 'BG' %}
        <ul class="list-group list-group-flush">
          <h2 class="p-3"> Cart Items: </h2>
          {% for order_item in order.items.all %}
            <li class="list-group-item">{{order_item.item.title}}, ${{order_item.get_final_price}}</li>
          {% empty %}
            <li class="list-group-item">
                You do not have any items in your order
            </li>
          {% endfor %}
        </ul>
      {% endif %}
      <div class="card-body text-center">
        <div id="paypal-button-container"></div>
      </div>
    </div>
  </div>
    <!-- Set up a container element for the button -->
    <div id="paypal-button-container"></div>
{% endblock content %}


{% block extra_scripts %}
    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=AclM7gtkokB1yTVsQtz9TewgvXxXK0bXVfc8Vo46-viO0-rY_ChW5XvmFBkOEB0HfHBwsFF2JhJfdstd&currency=USD"></script>

    <script>

        function getCookie(name) {
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
        }

        const csrftoken = getCookie('csrftoken');

        function createOrderCookie() {
          document.cookie = 'orderRefCode={{order.ref_code}}'
        }

        function completeOrder() {
          var url = "{% url 'core:complete'%}"
          
          fetch(url,{
            method:'POST',
            headers:{
              'Content-type':'application/json',
              'X-CSRFToken':csrftoken
            }
          }).then(
            createOrderCookie()
          )
        }

        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: {{order.get_total}}
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(orderData) {

                    console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                    var transaction = orderData.purchase_units[0].payments.captures[0]

                    completeOrder()

                });
            }


        }).render('#paypal-button-container');
    </script>
{% endblock extra_scripts %}

    

templates/product.htm
{%extends 'base_layout.htm'%}
{%load static%}

{%block extra_head%}
<link rel="stylesheet" href="{% static 'assets/product_description.css' %}">
{%endblock extra_head%}


{%block content%}
<section class="container sproduct my-5 pt-5">
    <div class="row mt-5">
        <div class="col-lg-5 col-md-12 col-12">
            <img class="img-fluid w-100 pb-1" id="mainImg" src="{{object.thumbnail.url}}" alt="Product thumbnail">

            <div class="small-img-group">
                <div class="small-img-col">
                    <img src="{{object.thumbnail.url}}" class="small-img" width="100%" alt="">
                </div>
                <div class="small-img-col">
                    <img src="{{object.display_image_one.url}}" class="small-img" width="100%" alt="">
                </div>
                <div class="small-img-col">
                    <img src="{{object.display_image_two.url}}" class="small-img" width="100%" alt="">
                </div>
                <div class="small-img-col">
                    <img src="{{object.display_image_three.url}}" class="small-img" width="100%" alt="">
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-12 col-12">
            <h6>{{ object.get_category_display }}</h6>
            <h3 class="py-4">{{object.title}}</h3>
            <h2>
                {% if object.discount_price %}
                <del>${{ object.price }}</del>
                <h2>${{ object.discount_price }}</h2>
                {% else %}
                <h2>${{ object.price }}</h2>
                {% endif %}
            </h2>
            <input type="number" value="1">
            <button class="buy-btn">
                <a href="{{object.get_add_to_cart_url}}">Add To Cart</a>
            </button>
            <button class="buy-btn">
                <a href="{{object.remove_from_cart_url}}">Remove From Cart</a>
            </button>
            
            <h4 class="mt-5 mb-5">Product Details</h4>
            <span>
                {{ object.description }}
            </span>
        </div>
    </div>
</section>
{%endblock%}

{% block extra_scripts %}
<script src="{%static 'assets/main.js'%}" type="text/javascript"></script>
{% endblock extra_scripts %}

templates/scripts.htm
{% load static %}
  
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

  $('.alert').alert()
</script>